const products = [
    {
        id: 0,
        name: "iPhone 11",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dolorum magni quibusdam magnam vitae commodi iusto est ea sequi cum.`,
        category: "iphone",
        price: 2999.99,
        image: "./img/products/iPhone11.jpg",
        sale: true,
        saleAmount: 350,
    },
    {
        id: 1,
        name: "iPhone 13",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dolorum magni quibusdam magnam vitae commodi iusto est ea sequi cum.`,
        category: "iphone",
        price: 4699.99,
        image: "./img/products/iPhone13.jpg",
    },
    {
        id: 2,
        name: "iPhone 12",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dolorum magni quibusdam magnam vitae commodi iusto est ea sequi cum.`,
        category: "iphone",
        price: 3899.99,
        image: "./img/products/iPhone12.jpg",
    },
    {
        id: 3,
        name: "iPhone 14 Pro",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dolorum magni quibusdam magnam vitae commodi iusto est ea sequi cum.`,
        category: "iphone",
        price: 7299.99,
        image: "./img/products/iPhone14_Pro.jpg",
    },
    {
        id: 4,
        name: "HUAWEI P30 Lite",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dolorum magni quibusdam magnam vitae commodi iusto est ea sequi cum.`,
        category: "huawei",
        price: 799.99,
        image: "./img/products/HUAWEI_P30_Lite.jpg",
        sale: true,
        saleAmount: 100,
    },
    {
        id: 5,
        name: "HUAWEI P40 Lite",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dolorum magni quibusdam magnam vitae commodi iusto est ea sequi cum.`,
        category: "huawei",
        price: 1399.99,
        image: "./img/products/HUAWEI_P40_Lite.jpg",
    },
    {
        id: 6,
        name: "Nokia 8.3",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dolorum magni quibusdam magnam vitae commodi iusto est ea sequi cum.`,
        category: "nokia",
        price: 999.99,
        image: "./img/products/Nokia_8.3.jpg",
    },
    {
        id: 7,
        name: "SAMSUNG Galaxy A51",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dolorum magni quibusdam magnam vitae commodi iusto est ea sequi cum.`,
        category: "samsung",
        price: 2199.99,
        image: "./img/products/SAMSUNG_Galaxy_A51.jpg",
        sale: true,
        saleAmount: 400,
    },
    {
        id: 8,
        name: "SAMSUNG Galaxy S10",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dolorum magni quibusdam magnam vitae commodi iusto est ea sequi cum.`,
        category: "samsung",
        price: 1499.99,
        image: "./img/products/SAMSUNG_Galaxy_S10.jpg",
    },
    {
        id: 9,
        name: "SAMSUNG Galaxy Z Flip",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dolorum magni quibusdam magnam vitae commodi iusto est ea sequi cum.`,
        category: "samsung",
        price: 5399.99,
        image: "./img/products/SAMSUNG_Galaxy_Z_Flip.jpg",
    },
]